### ISSUE TITLE
bug in filling track data

### ISSUE THREAD

**Issue by naodell** [CMS-HGCAL/reco-ntuples#30]
see here: https://github.com/CMS-HGCAL/reco-ntuples/blame/master/HGCalAnalysis/plugins/HGCalAnalysis.cc#L1033

**Comment by clelange** [comment]
Thanks for reporting this. Will you be able to fix this and submit a PR?

**Comment by naodell** [comment]
Sure thing.

**Comment by clelange** [comment]
addressed in #32
