### ISSUE TITLE
add GenParticle information

### ISSUE THREAD

**Issue by clelange** [CMS-HGCAL/reco-ntuples#37]
Add this information (4-vector , PDG ID + ?), but with a flag that is set to `False` (= do not write out) by default. What about filtering on status code?

**Comment by ajgilbert** [comment]
I think 4-vector, charge, pdgid and status code is the minimum we'd need, this is what I have on my branch so far (https://github.com/ajgilbert/reco-ntuples/commit/6fee757044dd3ff85a9d6aaaad6ae3e69c16c7b2) . We could also have an additional filter that keeps only the final state particles, which is all we'd need for clustering gen jets. Anything else you think we'd need?

**Comment by clelange** [comment]
I think filtering for final state particles would be good, unless you need the others for some other truth matching (for which currently the `TrackingParticle` collection is used, see https://github.com/ajgilbert/reco-ntuples/blob/6fee757044dd3ff85a9d6aaaad6ae3e69c16c7b2/HGCalAnalysis/plugins/HGCalAnalysis.cc#L310).
