### ISSUE TITLE
Raw rechits

### ISSUE THREAD

**Issue by artlbv** [CMS-HGCAL/reco-ntuples#42]
As mentioned on [mattermost](https://mattermost.web.cern.ch/cmg-hgcal/pl/tqwzgafpdtnd8eq549rfffr9hh), the possibility of storing raw rechits was partially removed by this commit: https://github.com/CMS-HGCAL/reco-ntuples/commit/204d368967b6eb004ece382b8b14a71e09d1d994, however, the flags still remain: https://github.com/CMS-HGCAL/reco-ntuples/blob/b67798405933ad4f0b8312a3889ef303c08f0c9b/HGCalAnalysis/test/exampleConfig.py#L29-L30

I'm having a look whether it's possible to keep the rawRechit flag working.

**Comment by clelange** [comment]
This flag is still functional, have a look at https://github.com/CMS-HGCAL/reco-ntuples/blob/master/HGCalAnalysis/plugins/HGCalAnalysis.cc#L993 - it steers whether hits that are not associated to layer clusters are dumped as well or not.

**Comment by artlbv** [comment]
Ok, I see! I was looking for a separate collection, but this way it naturally makes more sense. Thanks!
