### ISSUE TITLE
RecHit collection seems incomplete

### ISSUE THREAD

**Issue by clelange** [CMS-HGCAL/reco-ntuples#46]
When matching hits via `DetId` between `SimClusters` (based on what's stored in hits and fractions) and `RecHits`, there are more hits associated to the `SimCluster` than there are in the `RecHits` collections. This is not the case for `PFClusters`. The ntupliser code should dump all `RecHits` there are, so there must be some thresholds applied to the `RecHits` before being saved to the respective subdetector collections. This has not been the case in the past, so this is not a bug in the ntupliser, but a possibly a (desired?) feature in CMSSW. Investigating in CMSSW...

**Comment by beaudett** [comment]
Hi Clemens,
I might be off-topic, but in case, I prefer to write it down. There can be multiple SimHits associated to one single cell; indeed each SimHit is associated to the impinging particle. Therefore, in case of overlaps between showers, there can be several SimHits with the same DetId, while obviously, there is at most one RecHit per cell.

**Comment by clelange** [comment]
Hi Florian,
Thanks for your comment. The problem I see is that the `SimCluster` has additional hits that are not in the `RecHit` collections, so they seem to be lost...

**Comment by clelange** [comment]
I can confirm that this is the case in CMSSW as well, I checked for one of the RelVal samples:
`root://cmsxrootd.fnal.gov///store/relval/CMSSW_9_3_0_pre4/RelValDoublePiPt25Eta
17_27/GEN-SIM-RECO/93X_upgrade2023_realistic_v0_2023D17noPU-v1/00000/7E7B6645-038C-E711-8FC0-0CC47A4D767E.root`

**Comment by clelange** [comment]
Talking to Felice I found that this is probably due to some change in the digitiser and is OK/intended.
