### ISSUE TITLE
reachedEE logic

### ISSUE THREAD

**Issue by rovere** [CMS-HGCAL/reco-ntuples#61]
I'm not sure I can follow the logic of reachedEE in [this code snippet](https://github.com/CMS-HGCAL/reco-ntuples/blob/master/HGCalAnalysis/plugins/HGCalAnalysis.cc#L1122-L1159). To my limited understanding and debugging, the reachedEE==1 case is never a valid one.
Also the hardcoded 160 and 25 are something we should avoid as much as possible.

**Comment by artlbv** [comment]
If I remember correctly, @beaudett told me that `reachedEE = 1` means that the electron hits the barrel. So it does not happen for HGCAL, true, but could still be useful.

**Comment by beaudett** [comment]
Hello,

right, the reachedEE=1 is convenient to know if the the MC particle does 
not have the HGCAL-related quantites for the obvious reason it is reason 
it went into the barrel or if it is for a less obvious reason.

Florian

**Comment by rovere** [comment]
I see. Then, also in this case, I'd get rid (or customise) the hard-coded numbers and also add the `reachedEE` explanation in the Definitions.md.

**Comment by beaudett** [comment]
Hi Marco,

I suppose that configurable parameters if got enough for an ntupler  ?

Florian

**Comment by beaudett** [comment]
Hello Marco,

I started with the easiest changes.

As far as Definitions.md is concerned:
https://github.com/beaudett/reco-ntuples/blob/topic_fsimevent2/Definitions.md

For the hard-coded values, it is here:
https://github.com/beaudett/reco-ntuples/commit/d08a22d45234d89298d3ecf0a343671f0f83a1ca#diff-15765fecaeef229e305b918c8405f57a

With the corresponding changes in the config file.
https://github.com/beaudett/reco-ntuples/commit/d08a22d45234d89298d3ecf0a343671f0f83a1ca#diff-71cc2d53a5300edc7413159d809d80b8

Now, I must say that I am not so found of overloading the config file 
parameters that, most probably, nobody is going to change.
If you want it this way; no problem.
If you agree with me, I could put this parameters as constant values in 
the code with meaningful names; or I could make them as "invisible" 
parameters with default values.

Let me know what you prefer !
Cheers,
Florian
