### ISSUE TITLE
Installation recipe does not compile (CMSSW_10_2_0_pre1)

### ISSUE THREAD

**Issue by beaudett** [CMS-HGCAL/reco-ntuples#66]
Hello 
the recipe from the ReadMe does not work. 

The compilation fails with:
CMSSW_10_2_0_pre1/src/RecoNtuples/HGCalAnalysis/plugins/HGCalAnalysis.cc:1767:42: error: 'class hgcal::RecHitTools' has no member named 'getPositionLayer'; did you mean 'getPosition'?
     const GlobalPoint pos = recHitTools_.getPositionLayer(ilayer);
                                          ^~~~~~~~~~~~~~~~
I can take a look at it unless someone already knows how to fix it.
F.

**Comment by clelange** [comment]
Hello Florian,

Please use https://github.com/CMS-HGCAL/reco-ntuples/tree/TDR_geometry in case you really want to use `CMSSW_10_2_0_pre1`, see https://github.com/CMS-HGCAL/reco-ntuples/releases

I'll update the README within the next couple of days. Will leave this issue open until then.

**Comment by clelange** [comment]
Closed by #67 - @beaudett let me know if there's anything unclear/missing/not working.

10_3_X is currently under heavy development from the CMSSW-side, and the ntupliser is not yet updated to cope with sharing etc., see other issues.
