### ISSUE TITLE
Hardcoded total number of layers

### ISSUE THREAD

**Issue by apsallid** [CMS-HGCAL/reco-ntuples#70]
52 is given hardcoded when using retrieveLayerPositions. There are no longer 52 layers in V10 (D41) but 50 and it would be good to read those values from CMSSW. This issue here is related [1].  

[1]  https://github.com/cms-sw/cmssw/issues/26225

**Comment by clelange** [comment]
With https://github.com/cms-sw/cmssw/pull/27128 merged, we only need a new CMSSW release and can then remove hardcoded values.

**Comment by clelange** [comment]
The updated `RecHitTools` are now in a release: `CMSSW_11_0_0_pre3`.
